PostgreSQL:
  restart: always
  image: sameersbn/postgresql:12-20200524
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_NAME=test
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
  command: "--wal_keep_segments=32 --logging_collector=off"
  volumes:
    - postgresql:/var/lib/postgresql
